"""m1 segments and company_segments

Revision ID: 87d6ac25ff17
Revises: 
Create Date: 2026-06-07 17:34:29.282958
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '87d6ac25ff17'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('affinity_row_id', sa.String(length=50), nullable=True),
    sa.Column('organization_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('lead_status', sa.String(length=20), nullable=True),
    sa.Column('affinity_status', sa.String(length=100), nullable=True),
    sa.Column('owner', sa.String(length=300), nullable=True),
    sa.Column('tag', sa.String(length=200), nullable=True),
    sa.Column('investors', sa.Text(), nullable=True),
    sa.Column('investment_stage', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('industry_xange', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('year_founded', sa.Integer(), nullable=True),
    sa.Column('total_funding_usd', sa.Float(), nullable=True),
    sa.Column('total_funding_eur', sa.Float(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('dealroom_url', sa.String(length=500), nullable=True),
    sa.Column('last_email', sa.Date(), nullable=True),
    sa.Column('last_meeting', sa.Date(), nullable=True),
    sa.Column('next_meeting', sa.Date(), nullable=True),
    sa.Column('employees_current', sa.Integer(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_companies_affinity_row_id'), 'crm_companies', ['affinity_row_id'], unique=False)
    op.create_index(op.f('ix_crm_companies_country'), 'crm_companies', ['country'], unique=False)
    op.create_index(op.f('ix_crm_companies_lead_status'), 'crm_companies', ['lead_status'], unique=False)
    op.create_index(op.f('ix_crm_companies_organization_id'), 'crm_companies', ['organization_id'], unique=False)
    op.create_table('sectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('synthesis_headline', sa.Text(), nullable=True),
    sa.Column('synthesis_body', sa.Text(), nullable=True),
    sa.Column('synthesis_extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('claim_key', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('verified_by', sa.String(length=200), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'claim_key', name='uq_verification_claim')
    )
    op.create_index(op.f('ix_verifications_entity_id'), 'verifications', ['entity_id'], unique=False)
    op.create_index(op.f('ix_verifications_entity_type'), 'verifications', ['entity_type'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sector_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('founded', sa.String(length=50), nullable=True),
    sa.Column('geography', sa.String(length=200), nullable=True),
    sa.Column('funding_status', sa.String(length=200), nullable=True),
    sa.Column('funding_amount', sa.String(length=200), nullable=True),
    sa.Column('top_investors', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('primary_customer', sa.Text(), nullable=True),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('crm_company_id', sa.UUID(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_sector_id'), 'companies', ['sector_id'], unique=False)
    op.create_table('segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sector_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('focal_company', sa.String(length=200), nullable=True),
    sa.Column('thesis', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_insight', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_upload_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segments_sector_id'), 'segments', ['sector_id'], unique=False)
    op.create_table('uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sector_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.Column('competitive_potential', sa.Integer(), nullable=True),
    sa.Column('focal', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'segment_id', name='uq_company_segment')
    )
    op.create_index(op.f('ix_company_segments_company_id'), 'company_segments', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_segments_segment_id'), 'company_segments', ['segment_id'], unique=False)
    op.create_table('segment_synthesis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.Column('overview', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comparative', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('differentiation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('commentary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segment_synthesis_segment_id'), 'segment_synthesis', ['segment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segment_synthesis_segment_id'), table_name='segment_synthesis')
    op.drop_table('segment_synthesis')
    op.drop_index(op.f('ix_company_segments_segment_id'), table_name='company_segments')
    op.drop_index(op.f('ix_company_segments_company_id'), table_name='company_segments')
    op.drop_table('company_segments')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_segments_sector_id'), table_name='segments')
    op.drop_table('segments')
    op.drop_index(op.f('ix_companies_sector_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_verifications_entity_type'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_entity_id'), table_name='verifications')
    op.drop_table('verifications')
    op.drop_table('sectors')
    op.drop_index(op.f('ix_crm_companies_organization_id'), table_name='crm_companies')
    op.drop_index(op.f('ix_crm_companies_lead_status'), table_name='crm_companies')
    op.drop_index(op.f('ix_crm_companies_country'), table_name='crm_companies')
    op.drop_index(op.f('ix_crm_companies_affinity_row_id'), table_name='crm_companies')
    op.drop_table('crm_companies')
    # ### end Alembic commands ###
