"""m2 ai_enrichment

Revision ID: bd0d12029c46
Revises: 87d6ac25ff17
Create Date: 2026-06-07 18:12:19.626609
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'bd0d12029c46'
down_revision: Union[str, None] = '87d6ac25ff17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_enrichment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sector_id', sa.UUID(), nullable=False),
    sa.Column('focal_company_id', sa.UUID(), nullable=True),
    sa.Column('segment_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('query_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_enrichment_sector_id'), 'ai_enrichment', ['sector_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_enrichment_sector_id'), table_name='ai_enrichment')
    op.drop_table('ai_enrichment')
    # ### end Alembic commands ###
