"""sector synthesis_extra

Revision ID: eee22276b0f1
Revises: 24d257728b12
Create Date: 2026-06-07 12:47:38.971615
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'eee22276b0f1'
down_revision: Union[str, None] = '24d257728b12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sectors', sa.Column('synthesis_extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sectors', 'synthesis_extra')
    # ### end Alembic commands ###
